import cv2
from PIL import Image

img1 = cv2.imread(r'imagesq3/poly1.png',cv2.IMREAD_GRAYSCALE)
img2 = cv2.imread(r'imagesq3/poly2.png',cv2.IMREAD_GRAYSCALE)
img3 = cv2.imread(r'imagesq3/poly3.png',cv2.IMREAD_GRAYSCALE)
img4 = cv2.imread(r'imagesq3/poly4.png',cv2.IMREAD_GRAYSCALE)
img5 = cv2.imread(r'imagesq3/poly5.png',cv2.IMREAD_GRAYSCALE)
img6 = cv2.imread(r'imagesq3/poly6.png',cv2.IMREAD_GRAYSCALE)
img7 = cv2.imread(r'imagesq3/poly7.png',cv2.IMREAD_GRAYSCALE)
img8 = cv2.imread(r'imagesq3/poly8.png',cv2.IMREAD_GRAYSCALE)
img9 = cv2.imread(r'imagesq3/poly9.png',cv2.IMREAD_GRAYSCALE)
img10 = cv2.imread(r'imagesq3/poly10.png',cv2.IMREAD_GRAYSCALE)
img11 = cv2.imread(r'imagesq3/poly11.png',cv2.IMREAD_GRAYSCALE)
img12 = cv2.imread(r'imagesq3/poly12.png',cv2.IMREAD_GRAYSCALE)
img13 = cv2.imread(r'imagesq3/poly13.png',cv2.IMREAD_GRAYSCALE)
img14 = cv2.imread(r'imagesq3/poly14.png',cv2.IMREAD_GRAYSCALE)
# img15 = cv2.imread(r'imagesq3/poly15.png',cv2.IMREAD_GRAYSCALE)
new_size = (75,75)

Inew_img1 = Image.open(r'imagesq3/poly1.png')
Inew_img1n = Inew_img1.resize(new_size) 
Inew_img1n.save(r'newimagesq3/poly1.png')
Inew_img2 = Image.open(r'imagesq3/poly2.png')
Inew_img2n = Inew_img1.resize(new_size)
Inew_img2n.save(r'newimagesq3/poly2.png')
Inew_img3 = Image.open(r'imagesq3/poly3.png')
Inew_img3n = Inew_img3.resize(new_size) 
Inew_img3n.save(r'newimagesq3/poly3.png')
Inew_img4 = Image.open(r'imagesq3/poly4.png')
Inew_img4n = Inew_img4.resize(new_size) 
Inew_img4n.save(r'newimagesq3/poly4.png')
Inew_img5 = Image.open(r'imagesq3/poly5.png')
Inew_img5n = Inew_img5.resize(new_size) 
Inew_img5n.save(r'newimagesq3/poly5.png')
Inew_img6 = Image.open(r'imagesq3/poly6.png')
Inew_img6n = Inew_img6.resize(new_size) 
Inew_img6n.save(r'newimagesq3/poly6.png')
Inew_img7 = Image.open(r'imagesq3/poly7.png')
Inew_img7n = Inew_img7.resize(new_size) 
Inew_img7n.save(r'newimagesq3/poly7.png')
Inew_img8 = Image.open(r'imagesq3/poly8.png')
Inew_img8n = Inew_img8.resize(new_size) 
Inew_img8n.save(r'newimagesq3/poly8.png')
Inew_img9 = Image.open(r'imagesq3/poly9.png')
Inew_img9n = Inew_img9.resize(new_size) 
Inew_img9n.save(r'newimagesq3/poly9.png')
Inew_img10 = Image.open(r'imagesq3/poly10.png')
Inew_img10n = Inew_img10.resize(new_size) 
Inew_img10n.save(r'newimagesq3/poly10.png')
Inew_img11 = Image.open(r'imagesq3/poly11.png')
Inew_img11n = Inew_img11.resize(new_size) 
Inew_img11n.save(r'newimagesq3/poly11.png')
Inew_img12 = Image.open(r'imagesq3/poly12.png')
Inew_img12n = Inew_img12.resize(new_size) 
Inew_img12n.save(r'newimagesq3/poly12.png')
Inew_img13 = Image.open(r'imagesq3/poly13.png')
Inew_img13n = Inew_img13.resize(new_size) 
Inew_img13n.save(r'newimagesq3/poly13.png')
Inew_img14 = Image.open(r'imagesq3/poly14.png')
Inew_img14n = Inew_img14.resize(new_size) 
Inew_img14n.save(r'newimagesq3/poly14.png')



img1 = cv2.imread(r'newimagesq3/poly1.png',cv2.IMREAD_GRAYSCALE)
img2 = cv2.imread(r'newimagesq3/poly2.png',cv2.IMREAD_GRAYSCALE)
img3 = cv2.imread(r'newimagesq3/poly3.png',cv2.IMREAD_GRAYSCALE)
img4 = cv2.imread(r'newimagesq3/poly4.png',cv2.IMREAD_GRAYSCALE)
img5 = cv2.imread(r'newimagesq3/poly5.png',cv2.IMREAD_GRAYSCALE)
img6 = cv2.imread(r'newimagesq3/poly6.png',cv2.IMREAD_GRAYSCALE)
img7 = cv2.imread(r'newimagesq3/poly7.png',cv2.IMREAD_GRAYSCALE)
img8 = cv2.imread(r'newimagesq3/poly8.png',cv2.IMREAD_GRAYSCALE)
img9 = cv2.imread(r'newimagesq3/poly9.png',cv2.IMREAD_GRAYSCALE)
img10 = cv2.imread(r'newimagesq3/poly10.png',cv2.IMREAD_GRAYSCALE)
img11 = cv2.imread(r'newimagesq3/poly11.png',cv2.IMREAD_GRAYSCALE)
img12 = cv2.imread(r'newimagesq3/poly12.png',cv2.IMREAD_GRAYSCALE)
img13 = cv2.imread(r'newimagesq3/poly13.png',cv2.IMREAD_GRAYSCALE)
img14 = cv2.imread(r'newimagesq3/poly14.png',cv2.IMREAD_GRAYSCALE)


print(img1)
